name: Hank Quinlan, Horrible Cop

permalink: /blog/:year/:month/:day/:title

# 转换
markdown:    redcarpet
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Markdown 处理器
rdiscount:
  extensions: []

# redcarpet:
#   extensions: []

redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style